version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    environment:
      - SUPABASE_CLIENT_API_KEY=${SUPABASE_CLIENT_API_KEY}
    env_file:
      - .env

volumes:
  postgres_data: